scalar-labs/scalar-kubernetes

modules/azure/cosmosdb/main.tf
https://scalar-labs.atlassian.net/browse/DLT-7806
Changed an argument for `cosmosdb` module to adapt to scalar-labs/scalar-terraform#255.
=> Change argument for scalar-terraform cosmosdb module

.github/kubeval.sh
ref: #98 
https://helm.sh/docs/intro/quickstart/#initialize-a-helm-chart-repository
=> Fix helm repo in github actions

.github/kubeval.sh, .github/workflows/helm_charts_scalar.yml, README.md, benchmark/kelpie-only-pre.yaml, benchmark/kelpie-run.yaml, charts/stable/scalardl/README.md, charts/stable/scalardl/values.yaml, charts/stable/schema-loading/README.md, charts/stable/schema-loading/values.yaml, docs/DeployScalarDLAnsible.md, docs/DeployScalarDLHelm.md, docs/HelmValuesFiles.md, playbooks/playbook-deploy-scalardl.yml, playbooks/roles/scalardl/defaults/main.yml
https://scalar-labs.atlassian.net/browse/DLT-7849
Need to delete `DOCKERHUGB_ACCESS_TOKEN` and create `CR_PAT` in secrets.
=> Migrate to ghcr

conf/scalardl-custom-values.yaml
Fixed pod anti-affinity configuration.
I think the current configuration is a typo or something.
=> Make envoy and ledger pods evenly balanced to nodes as much as possible

docs/PortForwardingToK8sAPIInScalarTerraformNetwork.md, docs/PrepareBastionTool.md
https://scalar-labs.atlassian.net/browse/DLT-8330
=> Update docs for upgrade terraform to 0.14

charts/stable/schema-loading/Chart.yaml, charts/stable/schema-loading/README.md, charts/stable/schema-loading/templates/batchjob-schema-loading.yaml, charts/stable/schema-loading/values.yaml, conf/scalardl-custom-values.yaml, conf/schema-loading-custom-values.yaml
DynamoDB support integration with the helm chart
=> Update DynamoDB support to the helm chart

docs/DeployScalarDLAnsible.md, docs/GettingStarted.md, docs/HelmValuesFiles.md, docs/K8sLogCollectionGuide.md, docs/K8sMonitorGuide.md, docs/PortForwardingToK8sAPIInScalarTerraformNetwork.md
Ref: https://scalar-labs.atlassian.net/browse/DLT-8597
=> Fix broken links in documents

charts/stable/scalardl/Chart.yaml, charts/stable/scalardl/README.md, charts/stable/scalardl/templates/envoy/deployment.yaml, charts/stable/scalardl/templates/ledger/deployment.yaml, charts/stable/scalardl/values.yaml
https://scalar-labs.atlassian.net/browse/DLT-8668
https://scalar-labs.atlassian.net/browse/DLT-8614
https://scalar-labs.atlassian.net/browse/DLT-8331
- Fix `minReadySeconds` to `30` (`0` is working fine)
- Fix to use percentage for `maxSurge` and `maxUnavailable`
`maxSurge : 25%`
`maxUnavailable: 25%` 
- Fix `initialDelaySeconds` to `30` (`0` is working fine)
- Delete `readinessProbe`
=> Adjust pod options

playbooks/playbook-deploy-fluentbit.yml, playbooks/roles/fluentbit/defaults/main.yml, playbooks/roles/fluentbit/tasks/configuration.yml, playbooks/roles/fluentbit/tasks/copy.yml, playbooks/roles/fluentbit/tasks/deploy.yml
Refactoring fluentbit role for easy maintenance.
- DRY
- `yes` , `true` -> Unified to `true`
- yml indent
- Delete unnecessary codes
=> Refactoring fluentbit role

playbooks/playbook-deploy-prometheus.yml, playbooks/roles/prometheus/defaults/main.yml, playbooks/roles/prometheus/tasks/copy.yml, playbooks/roles/prometheus/tasks/dashboard.yml, playbooks/roles/prometheus/tasks/deploy.yml, playbooks/roles/prometheus/tasks/main.yml, playbooks/roles/prometheus/templates/prometheus-custom-values.yaml.j2
Refactoring prometheus role for easy maintenance.
- DRY
- `yes` , `true` -> Unified to `true`
- yml indent
- Fix deprecated (e.g, `with_items`)
- Delete unnecessary codes
=> Refactoring prometheus role

playbooks/roles/helm/defaults/main.yml
bug in #122 
ref: https://github.com/helm/helm/releases/tag/v3.5.2
=> Fix checksum for helm v3.5.2

docs/ManualDeploymentGuideScalarDLOnAzure.md
Minor modifications in manual deployment guide for Azure
=> Modify manual deployment guide for Azure

playbooks/playbook-deploy-scalardl.yml, playbooks/roles/scalardl/defaults/main.yml, playbooks/roles/scalardl/tasks/scalardl.yml, playbooks/roles/scalardl/tasks/schema.yml
https://scalar-labs.atlassian.net/browse/DLT-9450
It is preferable to use the latest version by default. (It's good that terratest can also test the latest version.)
=> Default to use latest version of helm-charts

conf/schema-loading-custom-values.yaml
Add `dynamoBaseResourceUnit` to custom values.
ref: https://github.com/scalar-labs/helm-charts/pull/7
=> Add dynamoBaseResourceUnit to schema loading custom values

docs/StepByStepManualDeploymentGuideScalarDLOnAzure.md, docs/StepbyStepManualDeploymentGuideScalarDLOnAzure.md
This PR is add step by step guide to deploy Scalar DL on Azure
Ref: https://scalar-labs.atlassian.net/browse/DLT-9222
=> Add step-by-step manual deployment guide for Azure

conf/scalardl-audit-custom-values.yaml, conf/scalardl-custom-values.yaml
The custom config of scalardl-audit.
=> Update/add for Auditor

README.md
Fix the README since it is pretty old.
We also need to reorganize/cleanup the docs under `/docs` directory.
=> Fix to match with the current statuses

docs/SetupDatabaseForAzure.md
I have updated the `SetupDatabaseForAzure` document by adding Azure Database for PostgreSQL section to it.
=> Add Azure Database for PostgreSQL

docs/AzureMarketplaceGuide.md, docs/ManualDeploymentGuideScalarDLOnAzure.md
This PR add the guide for using Azure Marketplace.
I created new document (`docs/AzureMarketplaceGuide.md`).
And I added the recommendation to use Azure Marketplace (Azure Container Registry) from AKS in the `docs/ManualDeploymentGuideScalarDLOnAzure.md`.
=> Add guide for using Azure Marketplace

docs/SetupDatabaseForAWS.md
I have updated the `SetupDatabaseForAWS.md` document by adding the Amazon Aurora section to it.
=> Add Amazon Aurora 

docs/ConfigureScalarDL.md
I have updated the ConfigureScalarDL.md guide with added details for configuring scalar DL and Auditor configuration files with JDBC databases. I have also made changes to the document to reduce the overall size.
Changed database-wise section for each configuration and updated in a general format.
Added tables with configuration properties for DynamoDB, Cosmos DB, and JDBC databases
This PR was created after closing an earlier PR for the same update which was closed due to too many comments(#174 )
=> Update configure scalar DL document

docs/ManualDeploymentGuideScalarDBServerOnAKS.md, docs/ManualDeploymentGuideScalarDBServerOnEKS.md
This PR updates the manual deployment guide of Scalar DB.
These documents explain the overview of steps for deploying Scalar DB on each Managed Kubernetes (EKS and AKS).
They have a lot of links to refer to other documents that describe the details of each step.
I will create/update those other documents that are referred from the documents of this PR.
Note: The target branch of this PR is `reorganize-docs`. After all documents are created/updated, I will create one PR to merge new docs to `master` branch.
=> Update manual deployment guide of Scalar DB

conf/scalar-loki-stack-custom-values.yaml, conf/scalar-prometheus-custom-values.yaml, docs/K8sLogCollectionGuide.md, docs/K8sMonitorGuide.md
This PR updates the monitoring and logging guide for Scalar products on a Kubernetes cluster.
Also, this PR adds sample custom values files of `kube-prometheus-stack` and `loki-stack` for Scalar product monitoring and logging.
Those sample files include some recommended/required configurations in the production environment.
=> Update monitoring and logging guide

docs/RegularCheck.md
This PR updates the regular check guide.
It describes how to check Kubernetes resources, Prometheus alerts, and Grafana metrics.
=> Update regular check guide

conf/scalar-loki-stack-custom-values.yaml, docs/AccessScalarProducts.md, docs/AzureMarketplaceGuide.md, docs/CreateAKSClusterForScalarProducts.md, docs/K8sLogCollectionGuide.md
This PR updates old product names to new (current) product names.
Sorry, I overlooked that old names remain in several documents...
=> Update product names

docs/CreateAKSClusterForScalarDLAuditor.md, docs/CreateEKSClusterForScalarDLAuditor.md
Before I forgot to add document links when I re-organized (created) documents. So, this PR adds document links.
N/A
I add links to the empty links and update titles based on the new created document.
N/A
=> Fix empty link

docs/ProductionChecklistForScalarDLAuditor.md, docs/ProductionChecklistForScalarDLLedger.md, docs/ProductionChecklistForScalarProducts.md
This PR adds the `Production checklist for ScalarDL Ledger` and `Production checklist for ScalarDL Auditor`.
This production checklist is similar to the ScalarDB Cluster production checklist. For example, Kubernetes cluster recommendations are basically the same as the ScalarDB Cluster's production checklist.
https://github.com/scalar-labs/scalar-kubernetes/pull/207
* Add new documents.
* Production checklist for ScalarDL Ledger
* Production checklist for ScalarDL Auditor
* Update index of production checklist.
N/A
=> Add production checklist for ScalarDL
