docs/EKSManualDeploymentGuide.md
=> Fix typo for eks doc

playbooks/roles/helm/defaults/main.yml
Stable location changed from `https://kubernetes-charts.storage.googleapis.com` to `https://charts.helm.sh/stable`.
Ref: https://helm.sh/blog/new-location-stable-incubator-charts/
=> Helm charts repo changed

charts/stable/scalardl/README.md, charts/stable/scalardl/README.md.gotmpl, charts/stable/scalardl/templates/ledger/deployment.yaml, charts/stable/scalardl/templates/ledger/secret.yaml, charts/stable/scalardl/values.yaml, charts/stable/schema-loading/README.md, charts/stable/schema-loading/README.md.gotmpl, charts/stable/schema-loading/templates/batchjob-schema-loading.yaml, charts/stable/schema-loading/templates/secret.yaml, charts/stable/schema-loading/values.yaml
Currently, database username and password are set directly in Deployment
`spec.template.spec.containers.env`, so it can be viewed by users with
any privileges. In general, credentials should only be visible to
administrators. So I change to use Secret objects for storing database
username and password.
Some users may want to use an existing Secret object. They can use
`ledger.existingSecret` to specify the Secret object name to use.
=> Use secret object for storing database username and password 

.github/workflows/helm_charts_scalar.yml, scripts/update-chart-docs.sh, scripts/verify-chart-docs.sh
This commit adds `update-chart-docs.sh` that updates README.md for each
Helm charts and `verify-chart-docs.sh` that checks if README.md needs to
be updated. `verify-chart-docs.sh` can be run in CI to prevent
forgetting to update README.md.
---
This PR is based on #92. Please review and merge it first.
=> Add a script file to update chart docs

charts/stable/scalardl/Chart.yaml, charts/stable/scalardl/README.md, charts/stable/scalardl/templates/ledger/service.yaml, charts/stable/scalardl/values.yaml
https://scalar-labs.atlassian.net/browse/DLT-8007
- Add srv records for ledger
```
[centos@bastion-1 ~]$ kubectl describe svc prod-scalardl-ledger-headless
Name:              prod-scalardl-ledger-headless
Namespace:         default
Labels:            app.kubernetes.io/app=ledger
app.kubernetes.io/instance=prod
app.kubernetes.io/managed-by=Helm
app.kubernetes.io/name=scalardl
app.kubernetes.io/version=2.1.0
helm.sh/chart=scalardl-1.2.0
Annotations:       meta.helm.sh/release-name: prod
meta.helm.sh/release-namespace: default
Selector:          app.kubernetes.io/app=ledger,app.kubernetes.io/instance=prod,app.kubernetes.io/name=scalardl
Type:              ClusterIP
IP:                None
Port:              scalardl  50051/TCP
TargetPort:        50051/TCP
Endpoints: …
```
=> Create srv records for scalardl

conf/scalardl-custom-values.yaml, docs/HelmValuesFiles.md
This PR fixes the following issues in the document 
Schema loading
---------------------
Using the current document after updating the `schema-loading-custom-values.yaml` following error occurs and schema loading not working.
```
ERROR: ["Unknown option: \"-P\""]
--cassandra                                   Operate for Cassandra
--cosmos                                      Operate for Cosmos DB
-h, --host DB_HOST                                Address of Cassandra like IP or URI address of your Cosmos DB account
-u, --user USERNAME                               Username of the database. This option is ignored when Cosmos DB.
-p, --password ACCOUNT_PASSWORD                   Password of Cassandra or Cosmos DB account
-f, --schema-file SCHEMA_JSON                     Schema file
-r, --ru …
```
=> Update document for changing Helm values for CosmosDB Configuration

docs/PrepareBastionTool.md, playbooks/playbook-install-tools.yml
Since `cloud_provider` is output in the  inventory file, so we can use it instead of `install_awscli` flag.
ref: https://github.com/scalar-labs/scalar-terraform/pull/289
=> Refactoring to use cloud_provider to install awscli role

playbooks/roles/prometheus/defaults/main.yml, playbooks/roles/prometheus/templates/prometheus-custom-values.yaml.j2
storageclass.storage.k8s.io "default" not found
```
Events:
Type     Reason             Age                From                Message
----     ------             ----               ----                -------
Warning  FailedScheduling   53s (x2 over 54s)  default-scheduler   0/6 nodes are available: 6 pod has unbound immediate PersistentVolumeClaims.
Normal   NotTriggerScaleUp  44s                cluster-autoscaler  pod didn't trigger scale-up (it wouldn't fit if a new node is added): 2 running "VolumeBinding" filter plugin for pod "prometheus-prometheus-prometheus-oper-prometheus-0": pod has unbound immediate PersistentVolumeClaims
```
```
[centos@bastion-1 ~]$ kubectl describe pvc prometheus-prometheus-prometheus-oper-prometheus-db-prometheus-prometheus-prometheus-oper-prometheus-0  -n …
```
=> Fix to use default  storage class for ebs

playbooks/roles/kubectl/defaults/main.yml, playbooks/roles/kubectl/tasks/install.yml, playbooks/roles/kubectl/tasks/setup.yml
- Upgrade kubectl to `1.19.10`
- Fix to use symlink
- Fix permission for `~/.kube/config`
```
[centos@bastion-1 ~]$ helm list
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/centos/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/centos/.kube/config
```
=> Refactoring kubectl role

playbooks/roles/prometheus/tasks/deploy.yml
The helm plugins are installed by `helm` role, so no longer needed in `prometheus` role.
https://github.com/scalar-labs/scalar-kubernetes/blob/31d00056c39f9fde2a2051d1410958940c92f583/playbooks/roles/helm/tasks/plugins.yml#L24-L30
=> Delete helm plugin installation in prometheus role

playbooks/playbook-deploy-scalardl.yml, playbooks/roles/scalardl/defaults/main.yml
The first version released on github pages is `1.2.3`.
https://github.com/scalar-labs/helm-charts/releases/tag/scalardl-1.2.3
=> Fix scalardl helm chart version to 1.2.3

conf/schema-loading-custom-values.yaml
Updates that correspond to [the PR](https://github.com/scalar-labs/helm-charts/pull/17/).
=> Update to make auditor schema applicable and make the corresponding chart runnable without the custom config

conf/scalardl-audit-custom-values.yaml, conf/scalardl-custom-values.yaml
Current Scalar DL Ledger and Auditor deployment guide do not support Scalar DL specific monitoring services. We will create a monitoring guide soon.
If these values are true, we need to create a namespace and deploy Prometheus.
=> Disable the default monitoring custom configuration values

docs/ManualDeploymentGuideScalarDLAuditorOnAWS.md
As per my current understanding, we do not need to configure the NACL rule for Ledger and Auditor environment because the security group controls ports at the instance level.
=> Remove NACL rule from manual deployment guide

docs/JpManualDeploymentGuideScalarDLAuditorOnAWS.md, docs/JpManualDeploymentGuideScalarDLOnAWS.md
This PR add the Scalar DL Manual Deployment Guide for EKS in Japanese.  
These docs based on the following two docs.  
* [Deploy Scalar DL on AWS](https://github.com/scalar-labs/scalar-kubernetes/blob/master/docs/ManualDeploymentGuideScalarDLOnAWS.md)
* [Deploy Scalar DL Auditor on AWS](https://github.com/scalar-labs/scalar-kubernetes/blob/master/docs/ManualDeploymentGuideScalarDLAuditorOnAWS.md)
However, there are some modified points, because I found some improvement points.  
So, I would like to ask review throughout of these document.  
=> Add japanese manual deployment guide of Scalar DL for EKS

docs/SetupDatabaseForAWS.md
I have created a guide to setting up databases for Scalar DL/Scalar DB in AWS. I had added DynamoDB as the first database in this document. But after making updates as per [PR](https://github.com/scalar-labs/scalar-kubernetes/pull/171) feedback the DynamoDB section was reduced to a few sentences. So I have added the AWS RDS databases section and created this new PR.
Check if all requirements are met
Check if the goal has been achieved
Check if you understand what you are explaining perfectly
Check if all the sentences are clear, concise, easy-to-understand, and well-thought English
Make sure there are no spelling mistakes and grammatical errors (some grammar issues exist which were shown in Grammarly which were difficult to resolve)
=> Create AWS supported database guide for Scalar DB/Scalar DL manual deployment guides

docs/SetupDatabaseForAWS.md
I have changed a wording mistake(Azure instead of AWS) in the `SetupDatabaseForAWS.md` guide.
I noticed it when checking the document. This is a recently created document by myself. 
I am sorry for the mistake and the inconvenience caused.
=> Word correction

conf/scalardb-custom-values.yaml
Updated `scalardb-custom-values.yaml` file with configurations for `podAntiAffinity` and `tolerations` as mentioned in this comment https://github.com/scalar-labs/scalar-kubernetes/pull/175#discussion_r885876064 related to scalar DB deployment guide. I have updated the custom file similar to the current `scalardl-custom-values.yaml` and tested it in deployment.
=> Update scalardb custom values

docs/ManualDeploymentGuideScalarDLAuditorOnAWS.md, docs/ManualDeploymentGuideScalarDLAuditorOnAzure.md, docs/ManualDeploymentGuideScalarDLOnAWS.md, docs/ManualDeploymentGuideScalarDLOnAzure.md
I have updated the links to set up database guides in both scalar DL deployment guides for AWS and Azure to set up database guides for AWS and Azure respectively.
=> Update links to setup database guide in scalar DL deployment guides

docs/ManualDeploymentGuideScalarDBServerOnAKS.md, docs/ManualDeploymentGuideScalarDLOnAWS.md, docs/ManualDeploymentGuideScalarDLOnAzure.md
This PR adds the explanation of `Taints` to the EKS/AKS deployment guide.
I will reorganize these documents, but I added these sentence since I think it is a critical issue.
If we don't add this `Taints` to the worker node, the pods of Scalar Products will not be deployed with [sample configurations](https://github.com/scalar-labs/scalar-kubernetes/tree/master/conf) since the sample configuration includes toleration to prevent application pods will be deployed to worker node for Scalar Products.
Also, in the [Japanese document](https://github.com/scalar-labs/scalar-kubernetes/blob/master/docs/JpManualDeploymentGuideScalarDLOnAWS.md#%E8%A6%81%E4%BB%B6-2), I already added the explanation of `Taints`.
=> Add requirement about `Taints` to the deployment guide

conf/scalardb-graphql-custom-values.yaml
This PR adds a custom values file for scalardb-graphql Helm chart.
This file is going to be referenced from the deployment guide. scalar-labs/scalardb-graphql#18
Currently, it covers AWS only. The database configurations and the Ingress annotations for other services should be added when needed.
=> Add custom values file for scalardb-graphql Helm chart

docs/AwsMarketplaceGuide.md
This PR adds the document about how to deploy Scalar products from AWS Marketplace.
In the AWS Marketplace, we can show an arbitrary URL to users on `Launch this software` page as follows.
I will add the URL of this document on the above page.
After that, users who subscribe to Scalar products can see how to deploy Scalar products (this document) from the AWS Marketplace page.
=> Add docs about how to deploy Scalar products from AWS Marketplace

docs/AwsMarketplaceGuide.md
This PR updates the following two things.
1. Add the URL of AWS Marketplace since they are available now.
1. Add description of Scalar DB GraphQL Server since it is available now.
=> Add AWS Marketplace URL and description of GraphQL Server

docs/AzureMarketplaceGuide.md
This PR updates the following two things in the Azure Marketplace doc.
1. Add description of Scalar DB GraphQL Server since it is available now.
1. Update the structure of the example part according to the following comment (update the structure same as AWS doc).
* https://github.com/scalar-labs/scalar-kubernetes/pull/184#discussion_r947446402
=> Add description of GraphQL Server in Azure Marketplace doc

conf/scalardb-custom-values.yaml, conf/scalardb-graphql-custom-values.yaml, conf/scalardl-audit-custom-values.yaml, conf/scalardl-custom-values.yaml, docs/CreateAKSClusterForScalarProducts.md, docs/CreateEKSClusterForScalarProducts.md
This PR adds new documents about how to create a k8s (EKS/AKS) cluster for the Scalar product deployment.
Mainly, these documents explain the `requirement` and `recommendation` points for the Scalar product deployment.
And, basically, this document shows the official document links for the concrete steps to create EKS and AKS.
Also, this PR updates the sample custom values file to reflect the new values (e.g., label, taint, resources limit etc...) of the updated document.
Note: The target branch of this PR is `reorganize-docs`. After all documents are created/updated, I will create one PR to merge new docs to `master` branch.
=> Add how to create k8s cluster (EKS/AKS) for Scalar products

conf/scalardb-custom-values.yaml, conf/scalardl-audit-custom-values.yaml, conf/scalardl-custom-values.yaml
This PR updates the sample custom values files.
The current sample custom values files are using the old way to configure `*.properties`.
So, I updated the old way to the following new way.
* Using `scalardb.databaseProperties`
* Using `ledger.ledgerProperties`
* Using `auditor.auditorProperties`
=> Update sample custom values file to use a new way

docs/AccessScalarProducts.md
This PR adds the document that describes how to access Scalar products on the Kubernetes environment. It describes two ways as follows.
* Using a Load Balancer in the production environment.
* Using the `kubectl port-forward` command for testing purposes on the bastion server.
=> Add guide how to access Scalar products on Kubernetes

docs/AwsMarketplaceGuide.md
**Note: We have to merge this PR after we publish pay-as-you-go ScalarDL on AWS Marketplace. We are working on it now.**
This PR adds the `how to deploy pay-as-you-go ScalarDL` section in the AWS Marketplace guide.
Also, I fixed product names in this document (`Scalar DB` -> `ScalarDB` / `Scalar DL` -> `ScalarDL`).
=> Support pay as you go scalardl in aws marketplace

docs/NetworkPeeringForScalarDLAuditor.md
This PR adds a new document that describes how to connect several private networks for ScalarDL Auditor mode. Since it is recommended to deploy Ledger and Auditor with different administrative domains, we must connect several private networks in the production environment.
=> Add network peering guide for ScalarDL Auditor mode

docs/CreateAKSClusterForScalarDB.md, docs/CreateAKSClusterForScalarDL.md, docs/CreateAKSClusterForScalarDLAuditor.md, docs/CreateAKSClusterForScalarProducts.md, docs/CreateEKSClusterForScalarDB.md, docs/CreateEKSClusterForScalarDL.md, docs/CreateEKSClusterForScalarDLAuditor.md, docs/CreateEKSClusterForScalarProducts.md, docs/ManualDeploymentGuideScalarDBServerOnAKS.md, docs/ManualDeploymentGuideScalarDBServerOnEKS.md, docs/ManualDeploymentGuideScalarDLAuditorOnAKS.md, docs/ManualDeploymentGuideScalarDLAuditorOnEKS.md, docs/ManualDeploymentGuideScalarDLOnAKS.md, docs/ManualDeploymentGuideScalarDLOnEKS.md
This PR updates the link (document) name in the manual deployment guide based on the https://github.com/scalar-labs/scalar-kubernetes/pull/200#discussion_r1268854512 in another PR.
=> Fix link name in deployment guide

docs/RestoreDatabase.md, docs/SetupDatabaseForAWS.md, docs/SetupDatabaseForAzure.md
This PR fixes broken links that were a result of reorganizing the ScalarDB "Getting Started" docs in the following PR: https://github.com/scalar-labs/scalardb/pull/990.
- https://github.com/scalar-labs/scalardb/pull/990
- Fixed broken links with working links that point to the appropriate headings in [Getting Started with ScalarDB](https://github.com/scalar-labs/scalardb/blob/master/docs/getting-started-with-scalardb.md).
> **Note**
> 
> In the future, it would be nice to change GitHub links to docs site links. However, this currently seems a bit difficult to do without having branches. I think we should avoid using absolute URLs in this case because we don't want to forcibly point users who are reading earlier versions of docs to the latest version of this doc. If that happens, users are …
=> Fix broken links pointing to deleted ScalarDB "Getting Started" docs

conf/scalardb-cluster-custom-values-indirect-mode.yaml, conf/scalardb-custom-values.yaml, conf/scalardl-audit-custom-values.yaml, conf/scalardl-custom-values.yaml, docs/CreateAKSClusterForScalarDB.md, docs/CreateAKSClusterForScalarDL.md, docs/CreateAKSClusterForScalarDLAuditor.md, docs/CreateEKSClusterForScalarDB.md, docs/CreateEKSClusterForScalarDBCluster.md, docs/CreateEKSClusterForScalarDL.md, docs/CreateEKSClusterForScalarDLAuditor.md
At this time, there are some descriptions of resources that Scalar Envoy uses.
However, this information is very old, and we don't have any concrete basis information.
In other words, we cannot use this information for resource estimation.
This information may cause unnecessary confusion.
So, we decided to remove this information.
Please take a look.
FYI: We will create an internal test environment (We call it PSIM in our internal document) that simulates production workload in the future. We will measure resources with some benchmarking workload on that environment in the future.
=> Remove inappropriate resource information of Envoy

docs/AwsMarketplaceGuide.md, docs/AzureMarketplaceGuide.md
We updated our recommendations for production environment. So, I updated marketplace guides based on the new recommendations.
N/A
* Remove `tag` or `version` configuration from custom values file. Now, we recommend to use default values in each Helm Chart.
* Remove `*.image.repository` configuration of Scalar Envoy. Now, we recommend to use the default (public) container repository of [Scalar Envoy](https://github.com/orgs/scalar-labs/packages/container/package/scalar-envoy).
* Mark ScalarDB Server and ScalarDB GraphQL as deprecated.
N/A
=> Update recommendations in Marketplace guides

docs/AwsMarketplaceGuide.md, docs/AzureMarketplaceGuide.md
Now, we start providing `ScalarDB Cluster (BYOL)` in AWS/Azure Marketplace.
* [AWS Marketplace](https://aws.amazon.com/marketplace/pp/prodview-alcwrmw6v4cfy) (Note: It is still in progress. Not published yet.)
* [Azure Marketplace](https://azuremarketplace.microsoft.com/ja-jp/marketplace/apps/scalarinc.scalardb?tab=PlansAndPrice) (Note: We already published.)
So, I updated each Marketplace Guide.
N/A
* Added sample configurations and commands when we use ScalarDB Cluster.
* Marked ScalarDB Server as `Deprecated` and removed sample configurations and commands about ScalarDB Server.
Some documents still have descriptions of `ScalarDB Server`. So, I will mark `ScalarDB Server` as `Deprecated` in all documents in another PR.
=> Add ScalarDB Cluster (BYOL) in Marketplace guides
